name = "smartposs"
main = "src/server/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

[triggers]
crons = ["0 * * * *"]

[vars]
ENVIRONMENT = "production"
APP_URL = "https://smartposs.mirakib2246.workers.dev"

[[d1_databases]]
binding = "DB"
database_name = "smartpos-db"
database_id = "ffd2658b-ac3e-4301-a36a-3f1a71e9a8ab"
migrations_dir = "migrations"
