import { ArrowRight, ArrowUpRight, CircleAlert, CreditCard, DollarSign, Store, UsersRound } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Alert } from '@/app/components/ui/alert';
import { Badge } from '@/app/components/ui/badge';
import { Button } from '@/app/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/app/components/ui/card';
import { StatCard } from '@/app/components/data-display/stat-card';
import { Skeleton } from '@/app/components/ui/skeleton';
import { api } from '@/core/services/api-client';
import { useAsync } from '@/core/hooks/use-async';
import { formatMoney } from '@/core/lib/formatters';
import type { AdminOverview } from '@/core/types/domain';

const demoOverview: AdminOverview = { activeTenants: 128, monthlyRecurringRevenue: 28400000, expiringSubscriptions: 9, churnRate: 2.4 };
export function AdminOverviewPage() { const demo = import.meta.env.VITE_DEMO_MODE === 'true'; const { data, loading, error, reload } = useAsync(() => demo ? Promise.resolve(demoOverview) : api.admin.overview(), [demo]); const overview = data ?? (demo ? demoOverview : null); if (loading && !overview) return <div className="space-y-6"><Skeleton className="h-16 w-96" /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[1, 2, 3, 4].map((item) => <Skeleton key={item} className="h-36 rounded-2xl" />)}</div></div>; return <div className="space-y-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow text-violet-500">Super Admin control plane</p><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">Platform health, in one view.</h1><p className="mt-2 text-sm text-muted-foreground">Keep the customer base healthy, plans clear, and renewals ahead of risk.</p></div><Button asChild variant="outline"><Link to="/admin/clients">Open client directory <ArrowRight className="h-4 w-4" /></Link></Button></div>{error && !demo ? <Alert tone="error" className="flex items-center justify-between">Could not load platform metrics. <Button variant="outline" size="sm" onClick={() => void reload()}>Retry</Button></Alert> : null}{overview ? <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Active tenants" value={overview.activeTenants.toLocaleString()} hint="trial + paid workspaces" icon={Store} trend={14} accent="blue" /><StatCard label="Monthly recurring revenue" value={formatMoney(overview.monthlyRecurringRevenue, 'BDT', '৳')} hint="current package run-rate" icon={DollarSign} trend={9.8} accent="emerald" /><StatCard label="Expiring soon" value={overview.expiringSubscriptions} hint="within the next 7 days" icon={CircleAlert} trend={-18} accent="amber" /><StatCard label="Churn rate" value={`${overview.churnRate}%`} hint="rolling tenant churn" icon={UsersRound} trend={-0.6} accent="violet" /></div><div className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><GrowthCard overview={overview} /><AdminActions /></div></> : null}</div>; }
function GrowthCard({ overview }: { overview: AdminOverview }) { return <Card className="overflow-hidden"><CardHeader className="flex-row items-start justify-between"><div><p className="eyebrow">Portfolio pulse</p><CardTitle className="mt-1 text-lg">Healthy momentum</CardTitle><p className="mt-1 text-sm text-muted-foreground">A directional read on the SaaS control plane.</p></div><Badge variant="success">On track</Badge></CardHeader><CardContent><div className="relative mt-3 h-48 overflow-hidden rounded-xl border border-border bg-gradient-to-br from-primary/[0.08] via-surface to-violet-500/[0.06] p-5"><div className="absolute inset-x-0 bottom-0 h-32 opacity-70" style={{ background: 'linear-gradient(135deg, transparent 10%, hsl(var(--primary) / .08) 10%, hsl(var(--primary) / .08) 11%, transparent 11%, transparent 20%, hsl(var(--primary) / .08) 20%, hsl(var(--primary) / .08) 21%, transparent 21%, transparent 32%, hsl(var(--primary) / .08) 32%, hsl(var(--primary) / .08) 33%, transparent 33%, transparent 47%, hsl(var(--primary) / .08) 47%, hsl(var(--primary) / .08) 48%, transparent 48%, transparent 65%, hsl(var(--primary) / .08) 65%, hsl(var(--primary) / .08) 66%, transparent 66%)' }} /><div className="relative flex h-full items-end justify-between gap-2">{[42, 53, 47, 64, 58, 77, 72, 88, 82, 100].map((height, index) => <div key={index} className="flex flex-1 flex-col justify-end gap-2"><div className="rounded-t-md bg-gradient-to-t from-primary/70 to-violet-400" style={{ height: `${height}%` }} /></div>)}</div></div><div className="mt-5 grid grid-cols-3 gap-4"><MiniMetric label="Live tenants" value={overview.activeTenants.toLocaleString()} detail="+14% this cycle" /><MiniMetric label="MRR" value={formatMoney(overview.monthlyRecurringRevenue, 'BDT', '৳')} detail="+9.8% this cycle" /><MiniMetric label="Retention" value={`${(100 - overview.churnRate).toFixed(1)}%`} detail="rolling 30 days" /></div></CardContent></Card>; }
function MiniMetric({ label, value, detail }: { label: string; value: string; detail: string }) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-lg font-semibold tracking-tight">{value}</p><p className="mt-1 text-[11px] text-success">{detail}</p></div>; }
function AdminActions() { const actions = [{ title: 'Review expiring plans', detail: 'Keep renewal conversations ahead of the curve.', href: '/admin/subscriptions', icon: CreditCard, tone: 'amber' }, { title: 'Manage plan limits', detail: 'Tune packages for the next growth segment.', href: '/admin/packages', icon: ArrowUpRight, tone: 'violet' }, { title: 'Open client directory', detail: 'Review status, branches, and workspace health.', href: '/admin/clients', icon: UsersRound, tone: 'blue' }]; return <Card><CardHeader><p className="eyebrow">Control room</p><CardTitle className="mt-1 text-lg">Admin actions</CardTitle></CardHeader><CardContent className="space-y-3">{actions.map((action) => { const Icon = action.icon; return <Link key={action.href} to={action.href} className="group flex items-center gap-3 rounded-xl border border-border p-3 transition-colors hover:border-primary/30 hover:bg-surface-muted"><span className={`rounded-lg p-2.5 ${action.tone === 'amber' ? 'bg-amber-500/10 text-amber-600' : action.tone === 'violet' ? 'bg-violet-500/10 text-violet-600' : 'bg-blue-500/10 text-blue-600'}`}><Icon className="h-4 w-4" /></span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold">{action.title}</span><span className="mt-1 block text-xs leading-5 text-muted-foreground">{action.detail}</span></span><ArrowRight className="h-4 w-4 text-muted-foreground group-hover:text-primary" /></Link>; })}</CardContent></Card>; }
