PRAGMA foreign_keys = ON;

-- SmartPOS Phase 1 core schema.
-- IDs are generated by the application with crypto.randomUUID() and stored as TEXT.
-- Monetary values are integer minor units (for example, cents or poisha) to avoid floating-point drift.

CREATE TABLE IF NOT EXISTS tenants (
  id TEXT PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE COLLATE NOCASE,
  status TEXT NOT NULL DEFAULT 'TRIAL' CHECK (status IN ('TRIAL', 'ACTIVE', 'SUSPENDED', 'ARCHIVED')),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS branches (
  id TEXT PRIMARY KEY NOT NULL,
  tenant_id TEXT NOT NULL,
  name TEXT NOT NULL,
  code TEXT NOT NULL,
  address TEXT,
  phone TEXT,
  is_primary INTEGER NOT NULL DEFAULT 0 CHECK (is_primary IN (0, 1)),
  status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE')),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  UNIQUE (tenant_id, code)
);

CREATE TABLE IF NOT EXISTS tenant_settings (
  tenant_id TEXT PRIMARY KEY NOT NULL,
  currency TEXT NOT NULL DEFAULT 'BDT',
  currency_symbol TEXT NOT NULL DEFAULT '৳',
  timezone TEXT NOT NULL DEFAULT 'Asia/Dhaka',
  tax_rate REAL NOT NULL DEFAULT 0 CHECK (tax_rate >= 0 AND tax_rate <= 100),
  invoice_prefix TEXT NOT NULL DEFAULT 'INV',
  receipt_header TEXT NOT NULL DEFAULT '',
  receipt_footer TEXT NOT NULL DEFAULT 'Thank you for your business.',
  receipt_paper_size TEXT NOT NULL DEFAULT '80mm' CHECK (receipt_paper_size IN ('58mm', '80mm')),
  enable_sms_alerts INTEGER NOT NULL DEFAULT 0 CHECK (enable_sms_alerts IN (0, 1)),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY NOT NULL,
  tenant_id TEXT NOT NULL,
  branch_id TEXT,
  email TEXT NOT NULL COLLATE NOCASE,
  password_hash TEXT NOT NULL,
  full_name TEXT NOT NULL,
  phone TEXT,
  is_super_admin INTEGER NOT NULL DEFAULT 0 CHECK (is_super_admin IN (0, 1)),
  status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INVITED', 'SUSPENDED', 'ARCHIVED')),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE SET NULL,
  UNIQUE (tenant_id, email)
);

CREATE TABLE IF NOT EXISTS roles (
  id TEXT PRIMARY KEY NOT NULL,
  tenant_id TEXT,
  name TEXT NOT NULL,
  description TEXT,
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  UNIQUE (tenant_id, name)
);

CREATE TABLE IF NOT EXISTS permissions (
  id TEXT PRIMARY KEY NOT NULL,
  code TEXT NOT NULL UNIQUE,
  module TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS role_permissions (
  role_id TEXT NOT NULL,
  permission_id TEXT NOT NULL,
  PRIMARY KEY (role_id, permission_id),
  FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
  FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_roles (
  user_id TEXT NOT NULL,
  role_id TEXT NOT NULL,
  PRIMARY KEY (user_id, role_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS packages (
  id TEXT PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  price_monthly INTEGER NOT NULL DEFAULT 0 CHECK (price_monthly >= 0),
  price_yearly INTEGER NOT NULL DEFAULT 0 CHECK (price_yearly >= 0),
  trial_days INTEGER NOT NULL DEFAULT 14 CHECK (trial_days >= 0 AND trial_days <= 365),
  max_users INTEGER NOT NULL DEFAULT 5 CHECK (max_users > 0),
  max_products INTEGER NOT NULL DEFAULT 100 CHECK (max_products > 0),
  max_branches INTEGER NOT NULL DEFAULT 1 CHECK (max_branches > 0),
  is_active INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1))
);

CREATE TABLE IF NOT EXISTS features (
  id TEXT PRIMARY KEY NOT NULL,
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS package_features (
  package_id TEXT NOT NULL,
  feature_id TEXT NOT NULL,
  PRIMARY KEY (package_id, feature_id),
  FOREIGN KEY (package_id) REFERENCES packages(id) ON DELETE CASCADE,
  FOREIGN KEY (feature_id) REFERENCES features(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS subscriptions (
  id TEXT PRIMARY KEY NOT NULL,
  tenant_id TEXT NOT NULL,
  package_id TEXT NOT NULL,
  start_date DATETIME NOT NULL,
  end_date DATETIME NOT NULL,
  status TEXT NOT NULL DEFAULT 'TRIAL' CHECK (status IN ('TRIAL', 'ACTIVE', 'EXPIRING', 'EXPIRED', 'SUSPENDED')),
  auto_renew INTEGER NOT NULL DEFAULT 1 CHECK (auto_renew IN (0, 1)),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY (package_id) REFERENCES packages(id) ON DELETE RESTRICT,
  CHECK (julianday(end_date) >= julianday(start_date))
);

CREATE TABLE IF NOT EXISTS subscription_payments (
  id TEXT PRIMARY KEY NOT NULL,
  subscription_id TEXT NOT NULL,
  tenant_id TEXT NOT NULL,
  amount INTEGER NOT NULL CHECK (amount >= 0),
  payment_method TEXT NOT NULL,
  transaction_ref TEXT,
  status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'PAID', 'FAILED', 'REFUNDED')),
  paid_at DATETIME,
  FOREIGN KEY (subscription_id) REFERENCES subscriptions(id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS payment_methods (
  id TEXT PRIMARY KEY NOT NULL,
  tenant_id TEXT NOT NULL,
  code TEXT NOT NULL,
  name TEXT NOT NULL,
  is_active INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  UNIQUE (tenant_id, code)
);

CREATE TABLE IF NOT EXISTS register_shifts (
  id TEXT PRIMARY KEY NOT NULL,
  tenant_id TEXT NOT NULL,
  branch_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  opened_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  closed_at DATETIME,
  opening_cash INTEGER NOT NULL DEFAULT 0 CHECK (opening_cash >= 0),
  closing_cash_expected INTEGER CHECK (closing_cash_expected >= 0),
  closing_cash_actual INTEGER CHECK (closing_cash_actual >= 0),
  note TEXT,
  status TEXT NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'CLOSED', 'VOID')),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE RESTRICT,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS notifications (
  id TEXT PRIMARY KEY NOT NULL,
  tenant_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  type TEXT NOT NULL DEFAULT 'INFO' CHECK (type IN ('INFO', 'SUCCESS', 'WARNING', 'ERROR')),
  is_read INTEGER NOT NULL DEFAULT 0 CHECK (is_read IN (0, 1)),
  metadata TEXT NOT NULL DEFAULT '{}',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id TEXT PRIMARY KEY NOT NULL,
  tenant_id TEXT NOT NULL,
  user_id TEXT,
  action TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id TEXT,
  ip_address TEXT,
  user_agent TEXT,
  metadata TEXT NOT NULL DEFAULT '{}',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_branches_tenant_status ON branches (tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_users_tenant_status ON users (tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_users_tenant_branch ON users (tenant_id, branch_id);
CREATE INDEX IF NOT EXISTS idx_users_email ON users (email);
CREATE INDEX IF NOT EXISTS idx_roles_tenant ON roles (tenant_id);
CREATE INDEX IF NOT EXISTS idx_role_permissions_permission ON role_permissions (permission_id);
CREATE INDEX IF NOT EXISTS idx_user_roles_role ON user_roles (role_id);
CREATE INDEX IF NOT EXISTS idx_package_features_feature ON package_features (feature_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_tenant_status ON subscriptions (tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_subscriptions_expiry ON subscriptions (status, end_date);
CREATE INDEX IF NOT EXISTS idx_subscription_payments_tenant_status ON subscription_payments (tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_subscription_payments_subscription ON subscription_payments (subscription_id);
CREATE INDEX IF NOT EXISTS idx_payment_methods_tenant_active ON payment_methods (tenant_id, is_active);
CREATE INDEX IF NOT EXISTS idx_register_shifts_tenant_branch_status ON register_shifts (tenant_id, branch_id, status);
CREATE INDEX IF NOT EXISTS idx_register_shifts_user ON register_shifts (user_id, opened_at);
CREATE INDEX IF NOT EXISTS idx_notifications_user_unread ON notifications (tenant_id, user_id, is_read, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_tenant_created ON audit_logs (tenant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_entity ON audit_logs (tenant_id, entity_type, entity_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_one_open_shift_per_branch ON register_shifts (branch_id) WHERE status = 'OPEN';
CREATE UNIQUE INDEX IF NOT EXISTS idx_one_current_subscription ON subscriptions (tenant_id) WHERE status IN ('TRIAL', 'ACTIVE', 'EXPIRING');

-- Platform permission catalog. Tenant provisioning assigns the system operator role to an initial user.
INSERT OR IGNORE INTO permissions (id, code, module) VALUES
  ('00000000-0000-4000-8000-000000000001', 'dashboard.read', 'dashboard'),
  ('00000000-0000-4000-8000-000000000002', 'settings.tenant.read', 'settings'),
  ('00000000-0000-4000-8000-000000000003', 'settings.tenant.manage', 'settings'),
  ('00000000-0000-4000-8000-000000000004', 'settings.branch.read', 'settings'),
  ('00000000-0000-4000-8000-000000000005', 'settings.branch.manage', 'settings'),
  ('00000000-0000-4000-8000-000000000006', 'pos.read', 'pos'),
  ('00000000-0000-4000-8000-000000000007', 'products.read', 'products'),
  ('00000000-0000-4000-8000-000000000008', 'inventory.read', 'inventory'),
  ('00000000-0000-4000-8000-000000000009', 'orders.read', 'orders'),
  ('00000000-0000-4000-8000-00000000000a', 'reports.read', 'reports');

INSERT OR IGNORE INTO roles (id, tenant_id, name, description)
VALUES ('00000000-0000-4000-8000-000000000010', NULL, 'System Operator', 'Default operational role for a provisioned workspace administrator.');

INSERT OR IGNORE INTO role_permissions (role_id, permission_id)
SELECT '00000000-0000-4000-8000-000000000010', id FROM permissions;
