import { ArrowRight, Boxes, CircleDollarSign, ClipboardList, CreditCard, MapPin, Package, Plus, ShieldCheck, ShoppingCart, UsersRound } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Alert } from '@/app/components/ui/alert';
import { Badge } from '@/app/components/ui/badge';
import { Button } from '@/app/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/app/components/ui/card';
import { Skeleton } from '@/app/components/ui/skeleton';
import { SalesChart } from '@/app/components/data-display/chart-card';
import { StatCard } from '@/app/components/data-display/stat-card';
import { useAsync } from '@/core/hooks/use-async';
import { useAuth } from '@/core/hooks/use-auth';
import { api } from '@/core/services/api-client';
import { daysLabel, formatDate, formatRelativeDate } from '@/core/lib/formatters';
import type { DashboardSnapshot } from '@/core/types/domain';

const demoSnapshot: DashboardSnapshot = { kpis: { activeUsers: 18, branches: 2, openRegisters: 3, unreadNotifications: 2 }, salesSeries: [{ day: 'Mon', sales: 182000 }, { day: 'Tue', sales: 236000 }, { day: 'Wed', sales: 198000 }, { day: 'Thu', sales: 288000 }, { day: 'Fri', sales: 326000 }, { day: 'Sat', sales: 412000 }, { day: 'Sun', sales: 368000 }], subscription: { id: 'demo-sub', tenantId: 'demo-tenant', packageId: 'growth', packageName: 'Growth', startDate: '2026-01-01T00:00:00.000Z', endDate: '2026-11-20T00:00:00.000Z', status: 'ACTIVE', autoRenew: true, daysRemaining: 45 }, activeBranch: { id: 'demo-branch', tenantId: 'demo-tenant', name: 'Gulshan Flagship', code: 'GUL', address: 'Gulshan Avenue, Dhaka', phone: '+880 1700 000000', isPrimary: true, status: 'ACTIVE', createdAt: '2025-01-01T00:00:00.000Z' }, recentActivity: [{ id: '1', action: 'updated', entityType: 'tenant_settings', createdAt: '2026-10-06T06:40:00.000Z' }, { id: '2', action: 'created', entityType: 'branch', createdAt: '2026-10-05T14:20:00.000Z' }, { id: '3', action: 'signed_in', entityType: 'user_session', createdAt: '2026-10-05T09:10:00.000Z' }] };

export function DashboardPage() {
  const { user, activeBranch } = useAuth();
  const demo = import.meta.env.VITE_DEMO_MODE === 'true';
  const { data, loading, error, reload } = useAsync(() => demo ? Promise.resolve(demoSnapshot) : api.tenant.summary(), [demo]);
  const snapshot = data ?? (demo ? demoSnapshot : null);
  if (loading && !snapshot) return <DashboardSkeleton />;
  return <div className="space-y-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow text-primary">Good morning, {user?.fullName.split(' ')[0] ?? 'operator'}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">Your business, at a glance.</h1><p className="mt-2 text-sm text-muted-foreground">A clear view of what needs attention across your workspace.</p></div><div className="flex items-center gap-2"><div className="hidden items-center gap-2 rounded-xl border border-border bg-surface px-3 py-2 text-xs text-muted-foreground sm:flex"><MapPin className="h-4 w-4 text-primary" /><span>{snapshot?.activeBranch?.name ?? activeBranch?.name ?? 'All branches'}</span></div><Button asChild><Link to="/pos"><ShoppingCart className="h-4 w-4" /> Open register</Link></Button></div></div>{error && !demo ? <Alert tone="error" className="flex items-center justify-between gap-4">We could not load the latest metrics. <Button variant="outline" size="sm" onClick={() => void reload()}>Retry</Button></Alert> : null}{snapshot ? <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Active team" value={snapshot.kpis.activeUsers} hint="people with access" icon={UsersRound} trend={8} accent="blue" /><StatCard label="Branches" value={snapshot.kpis.branches} hint="operating locations" icon={MapPin} trend={0} accent="violet" /><StatCard label="Open registers" value={snapshot.kpis.openRegisters} hint="across your workspace" icon={CircleDollarSign} trend={12} accent="emerald" /><StatCard label="Unread alerts" value={snapshot.kpis.unreadNotifications} hint="need your attention" icon={ShieldCheck} trend={snapshot.kpis.unreadNotifications ? -4 : 0} accent="amber" /></div><div className="grid gap-5 xl:grid-cols-[1.45fr_.75fr]"><SalesChart data={snapshot.salesSeries} /><SubscriptionCard subscription={snapshot.subscription} /></div><div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><QuickActions /><ActivityCard activities={snapshot.recentActivity} /></div></> : <Card><CardContent className="p-10 text-center text-sm text-muted-foreground">No dashboard data is available for this workspace.</CardContent></Card>}</div>;
}

function SubscriptionCard({ subscription }: { subscription: DashboardSnapshot['subscription'] }) { const urgent = !subscription || subscription.daysRemaining <= 7 || subscription.status === 'EXPIRED'; return <Card className="relative overflow-hidden border-primary/15 bg-gradient-to-br from-primary/[0.07] via-surface to-violet-500/[0.04]"><div className="absolute -right-12 -top-14 h-40 w-40 rounded-full bg-primary/[0.08]" /><CardHeader className="relative flex-row items-start justify-between"><div><p className="eyebrow text-primary">Plan & billing</p><CardTitle className="mt-1 text-lg">Subscription status</CardTitle></div><Badge variant={urgent ? 'warning' : 'success'}>{subscription?.status ?? 'Not active'}</Badge></CardHeader><CardContent className="relative">{subscription ? <><div className="flex items-end justify-between gap-4"><div><p className="text-3xl font-semibold tracking-tight">{daysLabel(subscription.daysRemaining)}</p><p className="mt-1 text-sm text-muted-foreground">{subscription.packageName} plan · renews {formatDate(subscription.endDate)}</p></div><CreditCard className="h-8 w-8 text-primary/70" /></div><div className="mt-6 h-2 overflow-hidden rounded-full bg-primary/10"><div className="h-full rounded-full bg-gradient-to-r from-primary to-violet-500" style={{ width: `${Math.max(5, Math.min(100, (subscription.daysRemaining / 90) * 100))}%` }} /></div><div className="mt-5 flex items-center justify-between gap-3 text-xs text-muted-foreground"><span>{subscription.autoRenew ? 'Auto-renew is on' : 'Manual renewal'}</span><Button asChild variant="soft" size="sm"><Link to="/settings">Review billing <ArrowRight className="h-3.5 w-3.5" /></Link></Button></div></> : <div className="py-2"><p className="text-sm text-muted-foreground">No active subscription is connected to this workspace.</p><Button asChild className="mt-5" size="sm"><Link to="/settings">Configure billing <ArrowRight className="h-3.5 w-3.5" /></Link></Button></div>}</CardContent></Card>; }

function QuickActions() { const actions = [{ icon: ShoppingCart, label: 'Open register', detail: 'Start a shift or checkout', href: '/pos' }, { icon: Package, label: 'Add product', detail: 'Grow your catalog', href: '/products' }, { icon: Boxes, label: 'Review inventory', detail: 'See stock movement', href: '/inventory' }, { icon: ClipboardList, label: 'View orders', detail: 'Follow fulfillment', href: '/orders' }]; return <Card><CardHeader className="flex-row items-center justify-between"><div><p className="eyebrow">Shortcuts</p><CardTitle className="mt-1 text-lg">Move the day forward</CardTitle></div><Plus className="h-5 w-5 text-muted-foreground" /></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2">{actions.map((action) => { const Icon = action.icon; return <Link key={action.href} to={action.href} className="group flex items-center gap-3 rounded-xl border border-border p-3 transition-all hover:-translate-y-0.5 hover:border-primary/30 hover:bg-accent/50"><span className="rounded-lg bg-accent p-2.5 text-primary"><Icon className="h-4 w-4" /></span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold">{action.label}</span><span className="mt-0.5 block truncate text-xs text-muted-foreground">{action.detail}</span></span><ArrowRight className="h-4 w-4 text-muted-foreground transition-transform group-hover:translate-x-1 group-hover:text-primary" /></Link>; })}</CardContent></Card>; }

function ActivityCard({ activities }: { activities: DashboardSnapshot['recentActivity'] }) { return <Card><CardHeader><p className="eyebrow">Audit trail</p><CardTitle className="mt-1 text-lg">Recent activity</CardTitle></CardHeader><CardContent>{activities.length ? <div className="space-y-4">{activities.map((activity) => <div key={activity.id} className="flex items-start gap-3"><span className="mt-1.5 h-2 w-2 shrink-0 rounded-full bg-primary" /><div className="min-w-0 flex-1"><p className="text-sm font-medium">{activity.action} <span className="text-muted-foreground">{activity.entityType.replaceAll('_', ' ')}</span></p><p className="mt-1 text-xs text-muted-foreground">{formatRelativeDate(activity.createdAt)}</p></div></div>)}</div> : <p className="text-sm text-muted-foreground">Workspace activity will appear here.</p>}</CardContent></Card>; }

function DashboardSkeleton() { return <div className="space-y-8"><div className="space-y-3"><Skeleton className="h-3 w-40" /><Skeleton className="h-10 w-80" /><Skeleton className="h-4 w-96" /></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[1, 2, 3, 4].map((item) => <Skeleton key={item} className="h-36 rounded-2xl" />)}</div><div className="grid gap-5 xl:grid-cols-[1.45fr_.75fr]"><Skeleton className="h-[360px] rounded-2xl" /><Skeleton className="h-[360px] rounded-2xl" /></div></div>; }
