import { BarChart3, Boxes, ClipboardList, Package, ShoppingCart, Sparkles } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Button } from '@/app/components/ui/button';
import { Card, CardContent } from '@/app/components/ui/card';
import { Badge } from '@/app/components/ui/badge';
import type { LucideIcon } from 'lucide-react';

const icons: Record<string, LucideIcon> = { pos: ShoppingCart, products: Package, inventory: Boxes, orders: ClipboardList, reports: BarChart3 };
const roadmap: Record<string, string[]> = { 'Point of sale': ['Register and shift context', 'Fast product lookup and barcode flows', 'Payments, split tender, and receipt print'], Products: ['Variant-aware catalog', 'Price lists and tax rules', 'Barcode and supplier identifiers'], Inventory: ['Branch-level stock ledger', 'Transfers, counts, and adjustments', 'Reorder thresholds and audit trail'], Orders: ['Unified order timeline', 'Returns and fulfillment states', 'Customer and payment history'], Reports: ['Branch and period filters', 'Margin and cash movement views', 'Export-ready operational datasets'] };

export function ModulePlaceholderPage({ module, eyebrow, icon }: { module: string; eyebrow: string; icon: string }) { const Icon = icons[icon] ?? Sparkles; return <div className="space-y-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow text-primary">{eyebrow}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">{module}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">This workspace is mapped to the SmartPOS foundation and will activate in the next operating module release.</p></div><Badge variant="warning">Phase 2 roadmap</Badge></div><Card className="overflow-hidden"><CardContent className="relative p-6 sm:p-10"><div className="absolute -right-16 -top-16 h-52 w-52 rounded-full bg-primary/[0.05]" /><div className="relative max-w-2xl"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-primary/10 text-primary"><Icon className="h-7 w-7" /></div><h2 className="mt-7 text-2xl font-semibold tracking-tight">The context is already in place.</h2><p className="mt-3 text-sm leading-7 text-muted-foreground">Tenant scope, branch selection, permissions, audit events, and PWA shell are shared with this module from day one. No separate admin surface or duplicate authentication layer will be needed.</p><div className="mt-8 grid gap-3 sm:grid-cols-3">{(roadmap[module] ?? []).map((item, index) => <div key={item} className="rounded-xl border border-border bg-surface-muted/50 p-4"><span className="text-xs font-bold text-primary">0{index + 1}</span><p className="mt-3 text-sm font-semibold leading-5">{item}</p></div>)}</div><div className="mt-8 flex flex-wrap gap-3"><Button asChild><Link to="/dashboard">Return to overview</Link></Button><Button asChild variant="outline"><Link to="/settings">Review workspace settings</Link></Button></div></div></CardContent></Card></div>; }
